name: Build, Push Docker Image and Deploy to GCP VM

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/lab45:latest .

    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/lab45:latest

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Pull & Run on VM
      run: |
        ssh -o StrictHostKeyChecking=no nastialetter@${{ secrets.VM_IP }} << 'EOF'
          docker pull ${{ secrets.DOCKER_USERNAME }}/lab45:latest
          docker stop lab45 || true
          docker rm lab45 || true
          docker run -d -p 80:80 --name lab45 ${{ secrets.DOCKER_USERNAME }}/lab45:latest
        EOF
